# Output Stats

## Setup

Import arcpy, pandas, numpy, and osgeo modules. Set the workspace path. Enable overwriting outputs

In [2]:
#import modules
import arcpy
from arcpy.ia import *
import pandas as pd
import numpy as np
from osgeo import gdal

arcpy.env.workspace = 'D:/masters_project/analysis/data' #edit to set work

arcpy.env.overwriteOutput = True #enable output overwrite

## Generate Summary Tables of Ecoregion Cover in Each Scenario

Count the number of cells of each ecoregion in the three scenarios

In [3]:
eco_dict = {'class':[], 'count':[]} #create an empty dictionary
eco = ['historical.tif', 'ssp370_class.tif', 'ssp585_class.tif'] #create a list of present day and predicted scenarios
workspace = 'D:/masters_project/analysis/data' #path as string

for file in eco: #loop for each raster in eco
    path = workspace+'/'+file #path
    raster = gdal.Open(path) #open raster
    band = raster.GetRasterBand(1) #assign band
    cols = raster.RasterXSize #assign columns
    rows = raster.RasterYSize #assign rows
    data = band.ReadAsArray(0, 0, cols, rows).astype(int) #read raster
    uni = np.unique(data,return_counts=True) #find unique values
    eco_dict['class'].append(uni[0]) #add class to dictionary
    eco_dict['count'].append(uni[1]) #add count to dictionary

df_eco = pd.DataFrame(eco_dict) #convert to dataframe
df_eco

                          class                                              count
0   [0, 1, 2, 3, 4, 5, 6, 7, 8]  [42395, 9242, 5468, 3811, 10918, 3202, 2705, 7...
1  [1, 2, 3, 4, 5, 6, 7, 8, 15]  [6165, 2254, 2581, 5453, 5810, 10459, 113, 105...
2  [1, 2, 3, 4, 5, 6, 7, 8, 15]  [6430, 1496, 2581, 5175, 5054, 12137, 34, 33, ...

Clean up the dataframe and save as a .csv

In [4]:
#reorganize df and explode lists
df_eco_exp = (pd.DataFrame({c:df_eco[c].explode() for c in eco_dict})
   .set_index('class', append=True)['count'] 
   .unstack(fill_value=0))

#remove NoData column
pixel_count = df_eco_exp.drop(df_eco_exp.columns[0], axis=1)
pixel_count = pixel_count.drop([15], axis=1)

pixel_count.insert(0, 'rowID', ['historical', 'ssp370', 'ssp585']) #add rowID column
pixel_count.to_csv('D:/masters_project/analysis/output_tables/pixel_counts.csv') #save as a .csv
pixel_count #check values look correct

pixel_count2 = pixel_count.drop(['rowID'], axis=1) #no rowid version for future math

pixel_count #check values look correct

class       rowID     1     2     3      4     5      6     7     8
0      historical  9242  5468  3811  10918  3202   2705  7782  2227
1          ssp370  6165  2254  2581   5453  5810  10459   113   105
2          ssp585  6430  1496  2581   5175  5054  12137    34    33

Calculate % cover for each ecoregion and save as a .csv

In [5]:
#add a new column that sums all the pixels in the row
pixel_count2['pixsum'] = pixel_count2.sum(axis=1)

#create a loop generating new columns for %cover 
i = 0
while i < 8: #loop for columns 1-8
    name = 'class'+str(i+1) #set name for new column, convert to string
    pixel_count2[name] = pixel_count2.iloc[:,i]/pixel_count2.pixsum*100 #append new column calculating %
    i = i+1 #add 1 to i value
    
eco_percent = pixel_count2.drop(pixel_count2.columns[0:9], axis=1) #drop count columns
eco_percent.insert(0, 'rowID', ['historical', 'ssp370', 'ssp585']) #add rowID column

eco_percent.to_csv('D:/masters_project/analysis/output_tables/eco_percent.csv') #save as a .csv
eco_percent #check if it looks right

class       rowID     class1     class2  ...    class6     class7    class8
0      historical  20.377026  12.056003  ...  5.964061  17.157976  4.910153
1          ssp370  18.715847   6.842744  ...  31.75167   0.343048  0.318761
2          ssp585   19.52034   4.541591  ...  36.84578   0.103218  0.100182

[3 rows x 9 columns]

Calculate %change in ecoregion cover between each pair of scenarios

In [10]:
pixel_count2 = pixel_count2.drop(pixel_count2.columns[8:17], axis=1) #remove % math from previous chunk

#%change math on rows
change_h370 = (pixel_count2.loc[1,:]-pixel_count2.loc[0,:])/pixel_count2.loc[0,:]*100 #%chng between historical and ssp370
change_h585 = (pixel_count2.loc[2,:]-pixel_count2.loc[0,:])/pixel_count2.loc[0,:]*100 #%chng between historical and ssp585
change_370_585 = (pixel_count2.loc[2,:]-pixel_count2.loc[1,:])/pixel_count2.loc[1,:]*100 #%chng between ssp370 and ssp585 

#add outputs to eco_change df
eco_change = pixel_count2.append(change_h370, ignore_index=True) #add h-370 row to eco% as new df eco_change
eco_change = eco_change.append(change_h585, ignore_index=True) #add h-585 row
eco_change = eco_change.append(change_370_585, ignore_index=True) #add 370-585 row

eco_change = eco_change.replace({np.nan:0}) #replace not a number with 0 again
eco_change2 = eco_change.drop([0, 1, 2]) #drop original cell count rows
eco_change2.insert(0, 'rowID', ['chng_h370', 'chng_h585', 'chng_370_585']) #add rowID column
eco_change2.to_csv('D:/masters_project/analysis/output_tables/eco_change.csv') #save as a .csv

eco_change2

class         rowID          1          2  ...           6          7          8
3         chng_h370 -33.293659 -58.778347  ...  286.654344 -98.547931 -95.285137
4         chng_h585 -30.426315 -72.640819  ...  348.687616 -99.563094 -98.518186
5      chng_370_585   4.298459 -33.629104  ...   16.043599 -69.911504 -68.571429

[3 rows x 9 columns]

## Generate Summary Tables For Protected Areas

Redo setup if needed

In [2]:
#import modules
import arcpy
from arcpy.ia import *
import pandas as pd
import numpy as np
from osgeo import gdal, osr

arcpy.env.workspace = 'D:/masters_project/analysis/data' #edit to change workspace pathing

arcpy.env.overwriteOutput = True #enable overwriting saved outputs

Clip all rasters to each protected area boundary. 3 scenarios x 18 pas = 54 output rasters

In [38]:
import arcpy
from arcpy import env
from arcpy.sa import * #import system models again

pa = ['KL_PA.shp', 'Barsey_RS.shp', 'Buxa_TR.shp', 'Chapramari_WS.shp', 'Fambong_Lho_WS.shp', 
      'Gorumara_NP.shp', 'Jigme_Khesar_SNR.shp', 'Jore_Pokhari_SS.shp', 'Kanchenjunga_CA.shp',
      'Khangchendzonga_BR.shp', 'Khitam_BS.shp', 'Kyongnosla_AS.shp', 'Mahananda_WS.shp',
     'Mainam_WS.shp', 'Pangolakha_WS.shp', 'Senchal_WS.shp', 'Singhalila_NP.shp', 'Singhba_RS.shp'] #list protected areas
clip = [] #empty list for outputs
n = 1 #set n to track output numbers

#clip historical data
for boundary in pa: #for each protected area
    x = ExtractByMask('historical.tif', boundary) #clip with extract by mask 
    save = 'D:/masters_project/analysis/data/intermediate/'+'hist_'+str(n)+'.tif' #set path for saving
    x.save(save) #save output to path
    name = 'hist_'+str(n)+'.tif' #set name for storage in clip[]
    clip.append(name) #add clip to list
    n += 1 #increase n for next protected area 

#clip ssp370 data
n = 1 #reset n
for boundary in pa: #for each protected area
    x = ExtractByMask('ssp370_class.tif', boundary) #clip
    save = 'D:/masters_project/analysis/data/intermediate/'+'ssp370_'+str(n)+'.tif' #set path for saving
    x.save(save) #save
    name = 'ssp370_'+str(n)+'.tif' #set raster name
    clip.append(name) #add clip to list
    n += 1 #increase n for next protected area 

#clip ssp585 data
n = 1 #reset n
for boundary in pa: #for each protected area
    x = ExtractByMask('ssp585_class.tif', boundary) #clip
    save = 'D:/masters_project/analysis/data/intermediate/'+'ssp585_'+str(n)+'.tif' #set path for saving
    x.save(save) #save
    name = 'ssp585_'+str(n)+'.tif' #set raster name
    clip.append(name) #add clip to list
    n += 1 #increase n for next protected area 
    
print(clip) #check output - should be 18 rasters for each scenarios

['hist_1.tif', 'hist_2.tif', 'hist_3.tif', 'hist_4.tif', 'hist_5.tif', 'hist_6.tif', 'hist_7.tif', 'hist_8.tif', 'hist_9.tif', 'hist_10.tif', 'hist_11.tif', 'hist_12.tif', 'hist_13.tif', 'hist_14.tif', 'hist_15.tif', 'hist_16.tif', 'hist_17.tif', 'hist_18.tif', 'ssp370_1.tif', 'ssp370_2.tif', 'ssp370_3.tif', 'ssp370_4.tif', 'ssp370_5.tif', 'ssp370_6.tif', 'ssp370_7.tif', 'ssp370_8.tif', 'ssp370_9.tif', 'ssp370_10.tif', 'ssp370_11.tif', 'ssp370_12.tif', 'ssp370_13.tif', 'ssp370_14.tif', 'ssp370_15.tif', 'ssp370_16.tif', 'ssp370_17.tif', 'ssp370_18.tif', 'ssp585_1.tif', 'ssp585_2.tif', 'ssp585_3.tif', 'ssp585_4.tif', 'ssp585_5.tif', 'ssp585_6.tif', 'ssp585_7.tif', 'ssp585_8.tif', 'ssp585_9.tif', 'ssp585_10.tif', 'ssp585_11.tif', 'ssp585_12.tif', 'ssp585_13.tif', 'ssp585_14.tif', 'ssp585_15.tif', 'ssp585_16.tif', 'ssp585_17.tif', 'ssp585_18.tif']

count the number of cells for each class in each clipped raster

In [39]:
workspace = 'D:/masters_project/analysis/data/intermediate' #list workspace as string

pa_dict = {'class':[], 'count':[]} #create an empty dictionary

for file in clip: #list of clipped rasters made earlier
    path = workspace+'/'+file #full path of input raster
    raster = gdal.Open(path) #open raster
    band = raster.GetRasterBand(1) #assign band
    Cols = raster.RasterXSize #assign columns
    Rows = raster.RasterYSize #assign rows
    data = band.ReadAsArray(0, 0, Cols, Rows).astype(int) #read raster
    uni = np.unique(data,return_counts=True) #find unique values
    pa_dict['class'].append(uni[0]) #add class to dictionary
    pa_dict['count'].append(uni[1]) #add count to dictionary

pa_df = pd.DataFrame(pa_dict) #convert to dataframe

pa_df #check output

                           class                                            count
0   [1, 2, 3, 4, 5, 6, 7, 8, 15]  [4264, 2639, 876, 743, 7, 302, 514, 903, 54327]
1                  [1, 3, 4, 15]                               [2, 105, 136, 450]
2               [4, 6, 7, 8, 15]                        [55, 188, 182, 903, 2272]
3                        [7, 15]                                         [18, 17]
4                        [4, 15]                                        [98, 225]
5                        [7, 15]                                       [145, 178]
6               [1, 2, 3, 4, 15]                          [801, 95, 147, 69, 886]
7                        [4, 15]                                          [2, 13]
8               [1, 2, 3, 4, 15]                     [1617, 1237, 206, 128, 1960]
9            [1, 2, 3, 4, 5, 15]                  [1600, 1313, 183, 110, 1, 3168]
10                       [5, 15]                                          [6, 10]
11                        [0, 1]                                         [46, 58]
12                    [6, 7, 15]                                  [114, 169, 399]
13                    [3, 4, 15]                                    [48, 31, 125]
14                 [1, 3, 4, 15]                               [137, 66, 25, 928]
15                       [4, 15]                                        [72, 108]
16                 [1, 3, 4, 15]                                [3, 121, 17, 251]
17                     [1, 2, 3]                                     [55, 26, 87]
18        [1, 2, 3, 4, 5, 6, 15]         [3217, 1009, 783, 939, 219, 1251, 39214]
19                 [3, 4, 5, 15]                               [11, 150, 15, 300]
20                    [4, 6, 15]                                   [1, 961, 1539]
21                       [6, 15]                                         [14, 10]
22                    [4, 5, 15]                                     [7, 64, 153]
23                    [5, 6, 15]                                    [25, 81, 132]
24              [1, 3, 4, 5, 15]                         [449, 179, 168, 10, 679]
25                       [4, 15]                                          [1, 11]
26           [1, 2, 3, 4, 5, 15]                  [1372, 458, 264, 163, 51, 1511]
27           [1, 2, 3, 4, 5, 15]                  [1247, 574, 239, 235, 29, 2356]
28                       [5, 15]                                           [5, 7]
29                 [1, 3, 4, 15]                                   [30, 7, 3, 37]
30                    [5, 6, 15]                                    [5, 194, 295]
31                       [4, 15]                                         [57, 93]
32              [1, 3, 4, 5, 15]                             [72, 31, 56, 6, 676]
33                 [4, 5, 6, 15]                                   [47, 2, 1, 93]
34                 [3, 4, 5, 15]                                 [45, 51, 7, 185]
35                     [0, 1, 3]                                      [51, 52, 7]
36        [1, 2, 3, 4, 5, 6, 15]          [3430, 568, 924, 946, 450, 1100, 39214]
37              [3, 4, 5, 6, 15]                             [16, 151, 3, 6, 300]
38                 [4, 5, 6, 15]                             [17, 178, 767, 1539]
39                       [6, 15]                                         [14, 10]
40                       [5, 15]                                        [71, 153]
41                    [5, 6, 15]                                    [3, 103, 132]
42              [1, 3, 4, 5, 15]                         [383, 231, 181, 11, 679]
43                       [4, 15]                                          [1, 11]
44           [1, 2, 3, 4, 5, 15]                  [1526, 211, 322, 187, 62, 1511]
45           [1, 2, 3, 4, 5, 15]                  [1386, 378, 256, 207, 97, 2356]
46                       [5, 15]                                           [5, 7]
47                     [0, 1, 3]                                     [37, 26, 14]
48                       [6, 15]                                       [199, 295]
49                    [4, 5, 15]                                     [40, 17, 93]
50              [1, 3, 4, 6, 15]                             [67, 30, 66, 2, 676]
51                 [4, 5, 6, 15]                                   [39, 2, 9, 93]
52                    [3, 4, 15]                                    [46, 57, 185]
53                 [1, 3, 5, 15]                                   [49, 9, 1, 51]

generate a list of rowID names for output tables

In [40]:
#generate list for rowID titles
pa = ['All_PA', 'Barsey_RS', 'Buxa_TR', 'Chapramari_WS', 'Fambong_Lho_WS', 
      'Gorumara_NP', 'Jigme_Khesar_SNR', 'Jore_Pokhari_SS', 'Kanchenjunga_CA',
      'Khangchendzonga_BR', 'Khitam_BS', 'Kyongnosla_AS', 'Mahananda',
     'Mainam_WS', 'Pangolakha_WS', 'Senchal_WS', 'Singhalila_NP', 'Singhba_RS'] #list all ecoregion names
raster = ['hist_', 'ssp_370_', 'ssp585_'] #list all scenarios
rowID = [] #empty list to store names

for x in raster: #loop for both scenario and ecoreion list
    for y in pa:
        name = x+y #combine raster and pa name
        rowID.append(name) #add to list

print(rowID) #check output

['hist_All_PA', 'hist_Barsey_RS', 'hist_Buxa_TR', 'hist_Chapramari_WS', 'hist_Fambong_Lho_WS', 'hist_Gorumara_NP', 'hist_Jigme_Khesar_SNR', 'hist_Jore_Pokhari_SS', 'hist_Kanchenjunga_CA', 'hist_Khangchendzonga_BR', 'hist_Khitam_BS', 'hist_Kyongnosla_AS', 'hist_Mahananda', 'hist_Mainam_WS', 'hist_Pangolakha_WS', 'hist_Senchal_WS', 'hist_Singhalila_NP', 'hist_Singhba_RS', 'ssp_370_All_PA', 'ssp_370_Barsey_RS', 'ssp_370_Buxa_TR', 'ssp_370_Chapramari_WS', 'ssp_370_Fambong_Lho_WS', 'ssp_370_Gorumara_NP', 'ssp_370_Jigme_Khesar_SNR', 'ssp_370_Jore_Pokhari_SS', 'ssp_370_Kanchenjunga_CA', 'ssp_370_Khangchendzonga_BR', 'ssp_370_Khitam_BS', 'ssp_370_Kyongnosla_AS', 'ssp_370_Mahananda', 'ssp_370_Mainam_WS', 'ssp_370_Pangolakha_WS', 'ssp_370_Senchal_WS', 'ssp_370_Singhalila_NP', 'ssp_370_Singhba_RS', 'ssp585_All_PA', 'ssp585_Barsey_RS', 'ssp585_Buxa_TR', 'ssp585_Chapramari_WS', 'ssp585_Fambong_Lho_WS', 'ssp585_Gorumara_NP', 'ssp585_Jigme_Khesar_SNR', 'ssp585_Jore_Pokhari_SS', 'ssp585_Kanchenjunga_CA', 'ssp585_Khangchendzonga_BR', 'ssp585_Khitam_BS', 'ssp585_Kyongnosla_AS', 'ssp585_Mahananda', 'ssp585_Mainam_WS', 'ssp585_Pangolakha_WS', 'ssp585_Senchal_WS', 'ssp585_Singhalila_NP', 'ssp585_Singhba_RS']

reorganize dataframe and explode

In [41]:
#reorganize df, explode
pa_df_exp = (pd.DataFrame({c:pa_df[c].explode() for c in pa_df})
   .set_index('class', append=True)['count'] 
   .unstack(fill_value=0))

#remove NoData column
pa_pixel_count = pa_df_exp.drop(pa_df_exp.columns[0], axis=1)
pa_pixel_count = pa_pixel_count.drop([15], axis=1)

pa_pixel_count.insert(0, 'rowID', rowID) #add rowID column
pa_pixel_count.to_csv('D:/masters_project/analysis/output_tables/pa_pixel_counts.csv') #save as a .csv

pa_pixel_count2 = pa_pixel_count.drop(['rowID'], axis=1) #no rowid version for future math

pa_pixel_count #check values look correct

class                       rowID     1     2    3    4    5     6    7    8
0                     hist_All_PA  4264  2639  876  743    7   302  514  903
1                  hist_Barsey_RS     2     0  105  136    0     0    0    0
2                    hist_Buxa_TR     0     0    0   55    0   188  182  903
3              hist_Chapramari_WS     0     0    0    0    0     0   18    0
4             hist_Fambong_Lho_WS     0     0    0   98    0     0    0    0
5                hist_Gorumara_NP     0     0    0    0    0     0  145    0
6           hist_Jigme_Khesar_SNR   801    95  147   69    0     0    0    0
7            hist_Jore_Pokhari_SS     0     0    0    2    0     0    0    0
8            hist_Kanchenjunga_CA  1617  1237  206  128    0     0    0    0
9         hist_Khangchendzonga_BR  1600  1313  183  110    1     0    0    0
10                 hist_Khitam_BS     0     0    0    0    6     0    0    0
11             hist_Kyongnosla_AS    58     0    0    0    0     0    0    0
12                 hist_Mahananda     0     0    0    0    0   114  169    0
13                 hist_Mainam_WS     0     0   48   31    0     0    0    0
14             hist_Pangolakha_WS   137     0   66   25    0     0    0    0
15                hist_Senchal_WS     0     0    0   72    0     0    0    0
16             hist_Singhalila_NP     3     0  121   17    0     0    0    0
17                hist_Singhba_RS    55    26   87    0    0     0    0    0
18                 ssp_370_All_PA  3217  1009  783  939  219  1251    0    0
19              ssp_370_Barsey_RS     0     0   11  150   15     0    0    0
20                ssp_370_Buxa_TR     0     0    0    1    0   961    0    0
21          ssp_370_Chapramari_WS     0     0    0    0    0    14    0    0
22         ssp_370_Fambong_Lho_WS     0     0    0    7   64     0    0    0
23            ssp_370_Gorumara_NP     0     0    0    0   25    81    0    0
24       ssp_370_Jigme_Khesar_SNR   449     0  179  168   10     0    0    0
25        ssp_370_Jore_Pokhari_SS     0     0    0    1    0     0    0    0
26        ssp_370_Kanchenjunga_CA  1372   458  264  163   51     0    0    0
27     ssp_370_Khangchendzonga_BR  1247   574  239  235   29     0    0    0
28              ssp_370_Khitam_BS     0     0    0    0    5     0    0    0
29          ssp_370_Kyongnosla_AS    30     0    7    3    0     0    0    0
30              ssp_370_Mahananda     0     0    0    0    5   194    0    0
31              ssp_370_Mainam_WS     0     0    0   57    0     0    0    0
32          ssp_370_Pangolakha_WS    72     0   31   56    6     0    0    0
33             ssp_370_Senchal_WS     0     0    0   47    2     1    0    0
34          ssp_370_Singhalila_NP     0     0   45   51    7     0    0    0
35             ssp_370_Singhba_RS    52     0    7    0    0     0    0    0
36                  ssp585_All_PA  3430   568  924  946  450  1100    0    0
37               ssp585_Barsey_RS     0     0   16  151    3     6    0    0
38                 ssp585_Buxa_TR     0     0    0   17  178   767    0    0
39           ssp585_Chapramari_WS     0     0    0    0    0    14    0    0
40          ssp585_Fambong_Lho_WS     0     0    0    0   71     0    0    0
41             ssp585_Gorumara_NP     0     0    0    0    3   103    0    0
42        ssp585_Jigme_Khesar_SNR   383     0  231  181   11     0    0    0
43         ssp585_Jore_Pokhari_SS     0     0    0    1    0     0    0    0
44         ssp585_Kanchenjunga_CA  1526   211  322  187   62     0    0    0
45      ssp585_Khangchendzonga_BR  1386   378  256  207   97     0    0    0
46               ssp585_Khitam_BS     0     0    0    0    5     0    0    0
47           ssp585_Kyongnosla_AS    26     0   14    0    0     0    0    0
48               ssp585_Mahananda     0     0    0    0    0   199    0    0
49               ssp585_Mainam_WS     0     0    0   40   17     0    0    0
50           ssp585_Pangolakha_WS    67     0   30   66    0     2    0    0
51              ssp585_Senchal_WS     0     0    0   39    2     9    0    0
52           ssp585_Singhalila_NP     0     0   46   57    0     0    0    0
53              ssp585_Singhba_RS    49     0    9    0    1     0    0    0

Calculate %cover of ecoregions in each row

In [42]:
#add a new column that sums all the pixels in the row
pa_pixel_count2['pixsum'] = pa_pixel_count2.sum(axis=1)

#create a loop generating new columns for 
i = 0
while i < 8: #loop for columns 1-8
    name = 'class'+str(i+1) #set name for new column, convert to string
    pa_pixel_count2[name] = pa_pixel_count2.iloc[:,i]/pa_pixel_count2.pixsum*100 #append new column calculating %
    i = i+1 #add 1 to i value
pa_eco_percent = pa_pixel_count2.drop(pa_pixel_count2.columns[0:9], axis=1) #drop count columns

pa_eco_percent.insert(0, 'rowID', rowID) #add rowID column
pa_eco_percent.to_csv('D:/masters_project/analysis/output_tables/pa_eco_percent.csv') #save as a .csv
pa_eco_percent #check if it looks right

class                       rowID     class1  ...     class7     class8
0                     hist_All_PA  41.608119  ...   5.015613   8.811475
1                  hist_Barsey_RS   0.823045  ...        0.0        0.0
2                    hist_Buxa_TR        0.0  ...  13.704819  67.996988
3              hist_Chapramari_WS        0.0  ...      100.0        0.0
4             hist_Fambong_Lho_WS        0.0  ...        0.0        0.0
5                hist_Gorumara_NP        0.0  ...      100.0        0.0
6           hist_Jigme_Khesar_SNR  72.032374  ...        0.0        0.0
7            hist_Jore_Pokhari_SS        0.0  ...        0.0        0.0
8            hist_Kanchenjunga_CA  50.721455  ...        0.0        0.0
9         hist_Khangchendzonga_BR  49.890864  ...        0.0        0.0
10                 hist_Khitam_BS        0.0  ...        0.0        0.0
11             hist_Kyongnosla_AS      100.0  ...        0.0        0.0
12                 hist_Mahananda        0.0  ...  59.717314        0.0
13                 hist_Mainam_WS        0.0  ...        0.0        0.0
14             hist_Pangolakha_WS  60.087719  ...        0.0        0.0
15                hist_Senchal_WS        0.0  ...        0.0        0.0
16             hist_Singhalila_NP    2.12766  ...        0.0        0.0
17                hist_Singhba_RS  32.738095  ...        0.0        0.0
18                 ssp_370_All_PA  43.367484  ...        0.0        0.0
19              ssp_370_Barsey_RS        0.0  ...        0.0        0.0
20                ssp_370_Buxa_TR        0.0  ...        0.0        0.0
21          ssp_370_Chapramari_WS        0.0  ...        0.0        0.0
22         ssp_370_Fambong_Lho_WS        0.0  ...        0.0        0.0
23            ssp_370_Gorumara_NP        0.0  ...        0.0        0.0
24       ssp_370_Jigme_Khesar_SNR  55.707196  ...        0.0        0.0
25        ssp_370_Jore_Pokhari_SS        0.0  ...        0.0        0.0
26        ssp_370_Kanchenjunga_CA  59.445407  ...        0.0        0.0
27     ssp_370_Khangchendzonga_BR  53.657487  ...        0.0        0.0
28              ssp_370_Khitam_BS        0.0  ...        0.0        0.0
29          ssp_370_Kyongnosla_AS       75.0  ...        0.0        0.0
30              ssp_370_Mahananda        0.0  ...        0.0        0.0
31              ssp_370_Mainam_WS        0.0  ...        0.0        0.0
32          ssp_370_Pangolakha_WS  43.636364  ...        0.0        0.0
33             ssp_370_Senchal_WS        0.0  ...        0.0        0.0
34          ssp_370_Singhalila_NP        0.0  ...        0.0        0.0
35             ssp_370_Singhba_RS  88.135593  ...        0.0        0.0
36                  ssp585_All_PA  46.238878  ...        0.0        0.0
37               ssp585_Barsey_RS        0.0  ...        0.0        0.0
38                 ssp585_Buxa_TR        0.0  ...        0.0        0.0
39           ssp585_Chapramari_WS        0.0  ...        0.0        0.0
40          ssp585_Fambong_Lho_WS        0.0  ...        0.0        0.0
41             ssp585_Gorumara_NP        0.0  ...        0.0        0.0
42        ssp585_Jigme_Khesar_SNR   47.51861  ...        0.0        0.0
43         ssp585_Jore_Pokhari_SS        0.0  ...        0.0        0.0
44         ssp585_Kanchenjunga_CA  66.117851  ...        0.0        0.0
45      ssp585_Khangchendzonga_BR  59.638554  ...        0.0        0.0
46               ssp585_Khitam_BS        0.0  ...        0.0        0.0
47           ssp585_Kyongnosla_AS       65.0  ...        0.0        0.0
48               ssp585_Mahananda        0.0  ...        0.0        0.0
49               ssp585_Mainam_WS        0.0  ...        0.0        0.0
50           ssp585_Pangolakha_WS  40.606061  ...        0.0        0.0
51              ssp585_Senchal_WS        0.0  ...        0.0        0.0
52           ssp585_Singhalila_NP        0.0  ...        0.0        0.0
53              ssp585_Singhba_RS  83.050847  ...        0.0        0.0

[54 rows x 9 columns]

Calculate %change between each pair of scenarios in each protected area

In [7]:
count = pd.read_csv('D:/masters_project/analysis/output_tables/pa_pixel_counts.csv') #call pixel count csv from before
count = count.drop(['rowID', 'Unnamed: 0'], axis=1) #drop null rows
count = count.T #transpose table

#generate names for rowIDs
pa = ['All_PA', 'Barsey_RS', 'Buxa_TR', 'Chapramari_WS', 'Fambong_Lho_WS', 
      'Gorumara_NP', 'Jigme_Khesar_SNR', 'Jore_Pokhari_SS', 'Kanchenjunga_CA',
      'Khangchendzonga_BR', 'Khitam_BS', 'Kyongnosla_AS', 'Mahananda',
     'Mainam_WS', 'Pangolakha_WS', 'Senchal_WS', 'Singhalila_NP', 'Singhba_RS'] #protected area names
change = ['h370_', 'h585_', '370_585_'] #%change categories
rowID = [] #empty list for rowid names

for x in change: #loop
    for y in pa:
        name = 'chng_'+x+y #combine each %change category with a pa
        rowID.append(name) #add rowID to list

#calculate %change between historical and ssp370 scenarios
i = 0
while i < 18: #loop for columns 0-17 (hist)
    name = rowID[i] #set column name as rowID
    j = i+18 #ssp370 is 18 rows beyond historical
    count[name] = (count.iloc[:, j]-count.iloc[:, i])/count.iloc[:, i]*100 #append new column calculating %chng
    i = i+1 #add 1 to i value

#calculate %change between historical and ssp585 scenarios
i = 0
while i < 18: #loop for columns 0-17 (hist)
    name = rowID[i+18] #set column name as rowID
    j = i+36 #ssp585 is 36 rows beyond historical
    count[name] = (count.iloc[:, j]-count.iloc[:, i])/count.iloc[:, i]*100 #append new column calculating %chng
    i = i+1 #add 1 to i value

#calculate %change between ssp370 and ssp585 scenarios
while i < 36: #loop for columns 18-35 (ssp370)
    name = rowID[i+18] #set column name as rowID
    j = i+18 #ssp585 is 18 rows beyond ssp370
    count[name] = (count.iloc[:, j]-count.iloc[:, i])/count.iloc[:, i]*100 #append new column calculating %chng
    i = i+1 #add 1 to i value

pa_eco_change = count.drop(count.columns[0:54], axis=1) #drop count columns
pa_eco_change = pa_eco_change.replace({np.nan:0}) #replace NaN from div by 0 errors with 0
pa_eco_change = pa_eco_change.replace({np.inf:100}) #replace inf from div by 0 errors with 100
pa_eco_change = pa_eco_change.T #transpose dataframe back

pa_eco_change.to_csv('D:/masters_project/analysis/output_tables/pa_eco_change.csv') #save to .csv

pa_eco_change #check outputs

                                          1           2  ...      7      8
chng_h370_All_PA                 -24.554409  -61.765820  ... -100.0 -100.0
chng_h370_Barsey_RS             -100.000000    0.000000  ...    0.0    0.0
chng_h370_Buxa_TR                  0.000000    0.000000  ... -100.0 -100.0
chng_h370_Chapramari_WS            0.000000    0.000000  ... -100.0    0.0
chng_h370_Fambong_Lho_WS           0.000000    0.000000  ...    0.0    0.0
chng_h370_Gorumara_NP              0.000000    0.000000  ... -100.0    0.0
chng_h370_Jigme_Khesar_SNR       -43.945069 -100.000000  ...    0.0    0.0
chng_h370_Jore_Pokhari_SS          0.000000    0.000000  ...    0.0    0.0
chng_h370_Kanchenjunga_CA        -15.151515  -62.974939  ...    0.0    0.0
chng_h370_Khangchendzonga_BR     -22.062500  -56.283321  ...    0.0    0.0
chng_h370_Khitam_BS                0.000000    0.000000  ...    0.0    0.0
chng_h370_Kyongnosla_AS          -48.275862    0.000000  ...    0.0    0.0
chng_h370_Mahananda                0.000000    0.000000  ... -100.0    0.0
chng_h370_Mainam_WS                0.000000    0.000000  ...    0.0    0.0
chng_h370_Pangolakha_WS          -47.445255    0.000000  ...    0.0    0.0
chng_h370_Senchal_WS               0.000000    0.000000  ...    0.0    0.0
chng_h370_Singhalila_NP         -100.000000    0.000000  ...    0.0    0.0
chng_h370_Singhba_RS              -5.454545 -100.000000  ...    0.0    0.0
chng_h585_All_PA                 -19.559099  -78.476696  ... -100.0 -100.0
chng_h585_Barsey_RS             -100.000000    0.000000  ...    0.0    0.0
chng_h585_Buxa_TR                  0.000000    0.000000  ... -100.0 -100.0
chng_h585_Chapramari_WS            0.000000    0.000000  ... -100.0    0.0
chng_h585_Fambong_Lho_WS           0.000000    0.000000  ...    0.0    0.0
chng_h585_Gorumara_NP              0.000000    0.000000  ... -100.0    0.0
chng_h585_Jigme_Khesar_SNR       -52.184769 -100.000000  ...    0.0    0.0
chng_h585_Jore_Pokhari_SS          0.000000    0.000000  ...    0.0    0.0
chng_h585_Kanchenjunga_CA         -5.627706  -82.942603  ...    0.0    0.0
chng_h585_Khangchendzonga_BR     -13.375000  -71.210967  ...    0.0    0.0
chng_h585_Khitam_BS                0.000000    0.000000  ...    0.0    0.0
chng_h585_Kyongnosla_AS          -55.172414    0.000000  ...    0.0    0.0
chng_h585_Mahananda                0.000000    0.000000  ... -100.0    0.0
chng_h585_Mainam_WS                0.000000    0.000000  ...    0.0    0.0
chng_h585_Pangolakha_WS          -51.094891    0.000000  ...    0.0    0.0
chng_h585_Senchal_WS               0.000000    0.000000  ...    0.0    0.0
chng_h585_Singhalila_NP         -100.000000    0.000000  ...    0.0    0.0
chng_h585_Singhba_RS             -10.909091 -100.000000  ...    0.0    0.0
chng_370_585_All_PA                6.621076  -43.706640  ...    0.0    0.0
chng_370_585_Barsey_RS             0.000000    0.000000  ...    0.0    0.0
chng_370_585_Buxa_TR               0.000000    0.000000  ...    0.0    0.0
chng_370_585_Chapramari_WS         0.000000    0.000000  ...    0.0    0.0
chng_370_585_Fambong_Lho_WS        0.000000    0.000000  ...    0.0    0.0
chng_370_585_Gorumara_NP           0.000000    0.000000  ...    0.0    0.0
chng_370_585_Jigme_Khesar_SNR    -14.699332    0.000000  ...    0.0    0.0
chng_370_585_Jore_Pokhari_SS       0.000000    0.000000  ...    0.0    0.0
chng_370_585_Kanchenjunga_CA      11.224490  -53.930131  ...    0.0    0.0
chng_370_585_Khangchendzonga_BR   11.146752  -34.146341  ...    0.0    0.0
chng_370_585_Khitam_BS             0.000000    0.000000  ...    0.0    0.0
chng_370_585_Kyongnosla_AS       -13.333333    0.000000  ...    0.0    0.0
chng_370_585_Mahananda             0.000000    0.000000  ...    0.0    0.0
chng_370_585_Mainam_WS             0.000000    0.000000  ...    0.0    0.0
chng_370_585_Pangolakha_WS        -6.944444    0.000000  ...    0.0    0.0
chng_370_585_Senchal_WS            0.000000    0.000000  ...    0.0    0.0
chng_370_585_Singhalila_NP         0.000000    0.000000  ...    0.0    0.0
chng_370_585_Singhba_RS           -5.769231    0.000000  ...    0.0    0.0

[54 rows x 8 columns]